

SECRET_KEY = 'wefb292h3d9be#@@YEBBCE2NION32UDFEBUE2U202hfeu2onwdsjdf'

MYSQL_HOST = 'localhost'
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'icac104104'
MYSQL_DB = 'LTCTMS'
MYSQL_CURSORCLASS = 'DictCursor'

SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://root:icac104104@localhost:3306/LTCTMS1'
SQLALCHEMY_TRACK_MODIFICATIONS = False
